config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get '/user' => "recipes#index", :as => :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :favourites, only: [:index, :show, :destroy]
    resources :memberships, only: [:index, :show, :destroy]
  end


  resources :recipes do
    collection do
      get :myrecipes
    end
    resources :favourites, only: [:new, :create]

    resources :reviews, only: [ :new, :create, :index, :destroy ]
  end

  resources :communities do

    resources :messages, except: [:destroy]
    resources :memberships

  end

  # resources :memberships, only: [] do
  #   collection do
  #     get :mymemberships
  #   end
  # end

  resources :messages, only: [:destroy]

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_community, only: [:new, :create, :index]

  def index
    # authorize @community
    @membership = Membership.find_by(user_id: current_user.id, community_id: @community.id)
    @messages = policy_scope(Message).where(community_id: @community.id)
    @message = Message.new
    # @memberships = policy_scope(Membership).where(current_user.id)


  end

  def show
    @message = Message.find(params[:id])
    authorize @message
    @new_message = Message.new
  end

  def new
    # we need @restaurant in our `simple_form_for`
    @message = Message.new
    authorize @message
    authorize @community
  end

  def create
    @message = Message.new(message_params)
    # we need `recipe_id` to associate review with corresponding recipe

    # authorize @community
    @message.user_id = current_user.id
    @message.community_id = @community.id
    authorize @message
    @message.save!
    redirect_to community_messages_path(@community, anchor:"message-id--#{@message.id}")
  end

  def destroy
    @message = Message.find(params[:id])
    authorize @message
    @message.destroy
    redirect_to community_messages_path(@message.community)
  end


  private

  def set_community
    @community = Community.find(params[:community_id])
  end

  def message_params
    params.require(:message).permit(:message)
  end
end

app/views/messages/_show.html.erb
<% unless message.message === "Hello!" && message.user_id == current_user.id %>
  <div id= "message-id--<%=message.id%>" class="comment mt-3">
    <div class="comment-heading">
      <% if message.user.photo.attached? %>
        <%= cl_image_tag message.user.photo.key , class: "mr-2 rounded", 'aria-haspopup': true, 'aria-expanded': false, size: "32x32" %>
      <% else %>
        <%= image_tag "https://cdn-icons-png.flaticon.com/512/190/190673.png?w=360", class: "mr-2 rounded", 'aria-haspopup': true, 'aria-expanded': false, size: "32x32" %>
      <% end %>
      <div class="comment-info">

        <%# <img  class="mr-2 rounded" style="width: 32px; height: 32px;" src="https://cdn-icons-png.flaticon.com/512/190/190673.png?w=360"> %>
          <% if (((message.created_at - DateTime.now)/(60*60*24)).abs.to_f.ceil) == 1 %>
              <p><strong><%= message.user.fullname%> </strong> <%= ((message.created_at - DateTime.now)/(60*60)).abs.to_i%> hours ago </p>
          <% elsif ((message.created_at - DateTime.now)/(60*60*24)).abs.to_f.ceil < 4  %>
              <p><strong><%= message.user.fullname%> </strong> <%= ((message.created_at - DateTime.now)/(60*60*24)).abs.to_i%> days ago </p>
          <% else %>
              <p><strong><%= message.user.fullname%> </strong> <%= message.created_at.strftime("%d/%m/%Y") %></p>
          <% end %>

      </div>
    </div>

  </div>

  <div class="comment-body text-black mx-5">
    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <%= message.message %>
    </p>
    <% if policy(message).destroy?%>
      <%= link_to  message_path(message), class:"danger-text mx-2", method: :delete, remote: true do %>
        <i class="fas fa-times"></i>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/messages/_show_welcome.html.erb
<div class="comment mt-3">
  <div class="comment-heading">
    <% if message.user.photo.attached? %>
      <%= cl_image_tag message.user.photo.key , class: "mr-2 rounded", 'aria-haspopup': true, 'aria-expanded': false, size: "32x32" %>
    <% else %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/190/190673.png?w=360", class: "mr-2 rounded", 'aria-haspopup': true, 'aria-expanded': false, size: "32x32" %>
    <% end %>
    <div class="comment-info">
      <%# <img  class="mr-2 rounded" style="width: 32px; height: 32px;" src="https://cdn-icons-png.flaticon.com/512/190/190673.png?w=360"> %>
      <% if (((message.created_at - DateTime.now)/(60*60*24)).abs.to_f.ceil) == 1 %>
          <p><strong><%= message.user.fullname%> </strong> <%= ((message.created_at - DateTime.now)/(60*60)).abs.to_i%> hours ago </p>
      <% elsif ((message.created_at - DateTime.now)/(60*60*24)).abs.to_f.ceil < 4  %>
          <p><strong><%= message.user.fullname%> </strong> <%= ((message.created_at - DateTime.now)/(60*60*24)).abs.to_i%> days ago </p>
      <% else %>
          <p><strong><%= message.user.fullname%> </strong> <%= message.created_at.strftime("%d/%m/%Y") %></p>
      <% end %>
    </div>
  </div>

</div>

<div class="comment-body text-black mx-5">
  <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
      <%= message.message %>
  </p>

</div>

app/views/messages/index.html.erb
<div class="message-container-fluid bg-color-primary5">
  <div class="blog--header" style="background-image: linear-gradient(rgba(18,149,117, 01), rgba(250,250,250,0.3)), url('<%= cl_image_path @community.photo.key, height: 500, crop: :fill %>')">
    <div class="header--text">
      <h1 class="text-black title--header"><%=@community.name  %></h1>
    </div>
  </div>
  <div class="container">
    <h3 class="text-black mt-3">Comments</h3>
    <div class="comment--section bg-color-primary5">
      <%= render partial: "show_welcome", locals: { message: @messages.first } %>
      <% @messages.slice(1..).each do |message| %>
      <%= render partial: "show", locals: { message: message } %>
      <% end %>
    </div>
  </div>
</div>

<%# ##MESAGE FORM %>

<% if  @membership || current_user.admin %>
  <div class="container">
    <%= simple_form_for [@community, @message], html: { class: "message--form p-5 mt-2 d-inline" },  remote: true do |f| %>
      <div class="d-flex flex-row align-items-center justify-content-start">
        <%= f.input :message, label: 'Insert your message', input_html: { class: "gray-border-rounded mr-4 p-2 adjust--with"}, wrapper_html: { class: "flex-grow-1"} ,
        :label_html => { :class => 'fs-6 text-black' } %>
        <%= button_tag type: 'submit', class: "btn btn-primary mx-2 p-2 mt-3" do %>
          <i class="fas fa-share"></i>
        <% end %>
      </div>
      <%# <div class="form-actions"> %>
        <%# <%= link_to "Leave",  community_membership_path(current_user.id, @membership.id), class:"btn btn-danger mb-3 ", method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>

      <%# </div> %>
    <% end %>
  </div>
<% else %>
  <div class="w-50 d-flex mx-5">
   <%= button_to "Join",  community_memberships_path(@community), method: :post, remote: true, class:"btn btn-outline-primary m-3"%>
  </div>
<% end %>

app/views/messages/show.html.erb
<h1><%=@community.name %></h1>