config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get '/user' => "recipes#index", :as => :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :favourites, only: [:index, :show, :destroy]
    resources :memberships, only: [:index, :show, :destroy]
  end


  resources :recipes do
    collection do
      get :myrecipes
    end
    resources :favourites, only: [:new, :create]

    resources :reviews, only: [ :new, :create, :index, :destroy ]
  end

  resources :communities do

    resources :messages, except: [:destroy]
    resources :memberships

  end

  # resources :memberships, only: [] do
  #   collection do
  #     get :mymemberships
  #   end
  # end

  resources :messages, only: [:destroy]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :favourites
  has_one_attached :photo

  validates :name, presence: true
  validates :ingredients, presence: true
  validates :difficulty, presence: true
  validates :time, presence: true
  validates :serves, presence: true
  validates :steps, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_ingredients,
    against: [ :name, :ingredients ],
    using: {
      tsearch: { prefix: true }
    }
 #scope :filter_by_difficulty, ->(tag_ids_arr) { joins(:tags).where( tags: { id: tag_ids_arr } ) }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # the page will be seen by every user
  skip_before_action :authenticate_user!, only: :index

  def index
    @recipes = policy_scope(Recipe).order(created_at: :desc).includes(:reviews)
    @recipes = Recipe.search_by_name_and_ingredients(params[:query]) if params[:query].present?
    @reviews = policy_scope(Review)
    @favourites = policy_scope(Favourite)
    @communities = policy_scope(Community)
    @recipes2 = policy_scope(Recipe)
    @search = params[:query] || params[:difficulty]
    @recipes = @recipes.select { |recipe| recipe.difficulty == params[:difficulty] } if params[:difficulty]
  end

  # if params[:query].present?
    # @recipes = policy_scope(Recipe).order(created_at: :desc)
    # @recipes = Recipe.search_by_address_and_description(params[:query]) #go to movie.rb file to understand reference

  # else
    # @recipes = policy_scope(Recipe).order(created_at: :desc)
  # end

  def show
    @recipe = Recipe.find(params[:id])
    # @booking = Booking.new

    authorize @recipe
    @review = Review.new
    authorize @review
    @favourites = policy_scope(Favourite)
    # authorize @booking
  end

  def myrecipes
    @recipes = Recipe.where(user: current_user).includes(:favourites)
    authorize @recipes
  end

  def new
    @recipe = Recipe.new
    authorize @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    authorize @recipe
    if @recipe.save
      redirect_to @recipe, notice: 'You have created a new recipe'
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.user = current_user
    authorize @recipe
    @recipe.update(recipe_params)
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'You have updated a recipe'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize @recipe
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
      authorize @recipe
    end

      # Only allow a list of trusted parameters through.
       def recipe_params
         params.require(:recipe).permit(:name, :ingredients, :difficulty, :time, :steps, :serves, :category, :photo)
       end
end

app/views/recipes/index.html.erb
<div class="container-fluid mt-4">
  <!-- SEARCH BAR -->
  <div class="search--bar--container mb-3">
    <div class="search--bar position-relative">
      <%= form_tag recipes_path, method: :get, :class => 'd-flex justify-content-start' do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control border--round--10 border-color-gray4  text-black bg-color-white py-2 text-gray1",
        placeholder: "Search by recipe or ingredients..."
      %>
      <% if params[:query] || params[:difficulty] %>
        <div class="position-absolute clear--search">
          <%= link_to recipes_path, request.query_parameters.merge({difficulty: nil, query: nil}), remote: true do%>
            <i class="far fa-times-circle"></i>
          <% end %>
        </div>
      <% end %>
        <%# <%= submit_tag "Search", class: "btn btn-primary mx-3 btn-sm text-white" %>
        <%#= button_tag type: 'submit', class: "btn btn-primary btn-sm ms-3 text-white" do %>
          <%#= image_tag "icon/filters.svg" %>
        <%# end %>
      <% end %>
    </div>
  </div>
  <div class="dropdown d-flex flex-row align-items-center">
    <div class="small text-gray1 pe-1">Diffculty:</div>
      <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        All
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><%= link_to 'easy', request.query_parameters.merge({difficulty: "easy"}), class: "dropdown-item" %></li>
        <li><%= link_to 'medium', request.query_parameters.merge({difficulty: "medium"}), class: "dropdown-item" %></li>
        <li><%= link_to 'hard', request.query_parameters.merge({difficulty: "hard"}), class: "dropdown-item" %></li>
      </ul>
    </div>
  <!-- END SEARCH BAR -->
  <!-- INDEX SEARCH RESULTS -->
  <% if @search %>
    <%# RESULT COUNT HEADER %>
    <div class="header--result">
      <h3 class="text-black"><%= @recipes.length  %> results...</h3>
    </div>
    <!--  CARDS LIST  -->
    <ul div class="m-0 p-0 grid">
      <% @recipes.each do |recipe| %>
        <li div class="m-0 p-0 d-flex ">
          <div class="card-global">
            <!-- link container -->
            <%= link_to recipe, class: "text-decoration-none" do %>
              <!-- image+rating container -->
              <div class="relative">
                <%= cl_image_tag recipe.photo.key, class: "img-cover" %>
                <!-- rating badge container -->
                <div class="absolute top-0 justify-content-end z-20 d-flex w-full smaller pt-2 pe-2">
                  <% rating = recipe.reviews.average(:rating).to_f.round(2) %>
                  <div class="badge_rating d-flex text-black <%= 'inactive--div' unless rating.positive? %>">
                    <%= image_tag "icon/rating-star.svg", class: "" %> <%= recipe.reviews.average(:rating).to_f.round(2)  %>
                  </div>
                <!-- rating badge container end -->
                </div>
              <!-- image+rating container end -->
              <!-- info -->
              <div class="small bold text-gray1 text-center mt-3"><%= recipe.name%></div>
              <!-- justify content between time and bookmark -->
              <div class=" d-flex justify-content-between align-items-center mt-3 pb-3 px-2">
                <!-- info time -->
                <div class="global_time smaller text-gray3">
                  Time <br>
                  <span class="bold text-gray1"> <%= recipe.time %></span>
                </div>
                <!-- info time end -->
                <!-- bookmark toggle -->
                <div class="d-flex h-full global_bookmark">
                  <% favourite = Favourite.find_by(user:current_user, recipe:recipe)  %>
                  <%if favourite %>
                    <%= link_to user_favourite_path(current_user, favourite), method: :delete, remote: true do%>
                      <%= image_tag "icon/bookmark-active.svg", class: "icon" %>
                    <% end %>
                  <% else %>
                    <%= link_to recipe_favourites_path(recipe), class: "icon_button", remote: true, method: :post do %>
                      <%= image_tag "icon/bookmark.svg", class: "icon" %>
                    <% end %>
                  <% end %>
                </div>
                <!-- bookmark toggle end -->
              </div>
              <!-- justify content between time and bookmark end -->
            <%end%>
            <!-- link container end -->
          </div>
        </li>
      <%end%>
    </ul>
      <!-- END CARDS LIST -->
      <!-- END INDEX SEARCH RESULTS -->
      <!-- INDEX  -->
    <% else %>
      <!-- CAROUSEL CARDS -->
      <div class="row flex-row flex-nowrap overflow-scroll hide-scrollbar">
        <% @recipes.first(6).each do |recipe| %>
          <div class="col-6 col-sm-4 ">
            <div class="card-slider relative w-full">
              <!-- link container -->
              <%= link_to recipe, class: "text-decoration-none" do %>
                <!-- image+rating container -->
                <div class="relative">
                  <%= cl_image_tag recipe.photo.key, class: "img-cover" %>
                  <!-- rating badge container -->
                  <div class="absolute top-0 justify-content-end z-20 d-flex w-full smaller pt-2 pe-2">
                  <% rating = recipe.reviews.average(:rating).to_f.round(2) %>
                    <div class="badge_rating d-flex text-black <%= 'inactive--div' unless rating.positive? %>">
                      <%= image_tag "icon/rating-star.svg" %> <%= recipe.reviews.average(:rating).to_f.round(2)  %>
                    </div>
                  </div>
                  <!-- rating badge container end -->
                </div>
                <!-- image+rating container end -->
                <!-- info -->
                <div class="small bold text-gray1 text-center mt-3"><%= recipe.name%></div>
                <!-- justify content between time and bookmark -->
                <div class=" d-flex justify-content-between align-items-center mt-3 pb-3 px-2">
                  <!-- info time -->
                  <div class="global_time smaller text-gray3">
                    Time <br>
                    <span class="bold text-gray1"> <%= recipe.time %></span>
                  </div>
                  <!-- info time end -->
                  <!-- bookmark toggle -->
                  <div class="d-flex h-full global_bookmark">
                    <% favourite = Favourite.find_by(user:current_user, recipe:recipe)  %>
                    <%if favourite %>
                      <%= link_to user_favourite_path(current_user, favourite), class: "icon_button", remote: true, method: :delete do%>
                        <%= image_tag "icon/bookmark-active.svg", class: "icon" %>
                      <% end %>
                    <% else %>
                      <%= link_to recipe_favourites_path(recipe), class: "icon_button", remote: true, method: :post do %>
                        <%= image_tag "icon/bookmark.svg", class: "icon" %>
                      <% end %>
                    <% end %>
                  </div>
                  <!-- bookmark toggle end -->
                </div>
                <!-- justify content between time and bookmark end -->
              <%end%>
              <!-- link container end -->
            </div>
          </div>
        <%end%>
      </div>
      <!-- END CAROUSEL CARDS -->
      <!-- RECIPES RECOMMENDATIONS -->
      <h1 class="normal bold text-black mt-3">5 recipes to make this week </h1>
      <div class="row flex-row flex-nowrap overflow-scroll hide-scrollbar">
        <% @recipes2.sample(6).each do |recipe| %>
          <div class="col-12 col-lg-6 ">
            <div class="card-slider relative w-full">
              <!-- link container -->
              <%= link_to recipe, class: "text-decoration-none" do %>
                <!-- image+rating container -->
                <div class="relative">
                  <%= cl_image_tag recipe.photo.key, class: "img-cover gradient--image" %>
                  <!-- rating badge container -->
                  <div class="absolute top-0 justify-content-end z-20 d-flex w-full smaller pt-2 pe-2">
                    <% rating = recipe.reviews.average(:rating).to_f.round(2) %>
                    <div class="badge_rating d-flex text-black <%= 'inactive--div' unless rating.positive? %>">
                      <%= image_tag "icon/rating-star.svg" %> <%= recipe.reviews.average(:rating).to_f.round(2)  %>
                    </div>
                  </div>
                  <!-- rating badge container end -->
                </div>
                <!-- image+rating container end -->
                <!-- info -->
                <div class="small bold text-gray1 text-center mt-3"><%= recipe.name%></div>
                <!-- justify content between time and bookmark -->
                <div class=" d-flex justify-content-between align-items-center mt-3 pb-3 px-2">
                  <!-- info time -->
                  <div class="global_time smaller text-gray3">
                    Time <br>
                    <span class="bold text-gray1"> <%= recipe.time %></span>
                  </div>
                  <!-- info time end -->
                  <!-- bookmark toggle -->
                  <div class="d-flex h-full global_bookmark">
                    <% favourite = Favourite.find_by(user:current_user, recipe:recipe)  %>
                    <%if favourite %>
                      <%= link_to user_favourite_path(current_user, favourite), class: "icon_button", remote: true, method: :delete do%>
                        <%= image_tag "icon/bookmark-active.svg", class: "icon" %>
                      <% end %>
                    <% else %>
                      <%= link_to recipe_favourites_path(recipe), class: "icon_button", remote: true, method: :post do %>
                        <%= image_tag "icon/bookmark.svg", class: "icon" %>
                      <% end %>
                    <% end %>
                  </div>
                  <!-- bookmark toggle end -->
                </div>
                <!-- justify content between time and bookmark end -->
              <%end%>
              <!-- link container end -->
            </div>
          </div>
        <%end%>
      </div>
      <!-- END RECIPES RECOMMENDATIONS -->
      <!-- COMMUNITITES FOR YOU -->
      <div class="container-fluid mt-4 px-0">
        <h2 class="normal bold text-black">Communities for you</h2>
        <div class="row flex-row flex-nowrap overflow-scroll hide-scrollbar">
          <% @communities.first(5).each do |community|  %>
            <div class="col-6 col-sm-4 col-lg-3 community--slider">
              <div class="card-slider relative w-full community--slider mb-3 community-index-card">
                <%= cl_image_tag community.photo.key, class: "img-cover gradient--image" %>
                <%= link_to community, class: "text-decoration-none" do %>
                  <div class="small bold text-gray1 text-center bg-color-primary2 text-white"><%= community.name%></div>
                <%end%>
              </div>
            </div>
          <%end%>
        </div>
      </div>
      <!-- END COMMUNITITES FOR YOU -->
    <% end %>
    <!-- END INDEX  -->
  </div>

app/views/recipes/myrecipes.html.erb
<div class="container">
  <h1 class="text-black mt-3 letter--space">Your Recipes</h1>
    <% if @recipes.length === 0 %>
      <h4 class="text-gray3 letter--space">You haven't created any recipes yet!</h4>
      <%= image_tag "background-images/no_communities.jpg", class: "d-flex w-50 border--round my-3"  %>
      <%= link_to "Create your first recipe", new_recipe_path, class: "decoration--none mb-3" %>
    <% else %>
    <div class="container--favorite my-4">
      <% @recipes.each do |recipe| %>
        <div class="card--favorite m-3" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.8)), url('<%= cl_image_path recipe.photo.key, height: 300 %>')">
          <div class="title--card">
            <div class="bookmark mx-3">
              <% favourite = Favourite.find_by(user:current_user, recipe:recipe)  %>
              <%if favourite %>
                      <%= link_to user_favourite_path(current_user, favourite), remote: true, method: :delete do%>
                        <%= image_tag "icon/bookmark-active.svg", class: "icon" %>
                      <% end %>
                    <% else %>
                      <%= link_to recipe_favourites_path(recipe), class: "icon_button", remote: true, method: :post do %>
                        <%= image_tag "icon/bookmark.svg", class: "icon" %>
                      <% end %>
                    <% end %>
            </div>
            <div class="badge_rating d-flex text-black m-2">
              <%= image_tag "icon/rating-star.svg" %> <%= recipe.reviews.average(:rating).to_f.round(2)  %>
            </div>
          </div>
          <div class="card--favorite--data">
            <%= link_to recipe_path(recipe), class:"text-decoration-none" do%>
              <h3 class="text-white favorite--title m-3"><%= recipe.name  %></h3>
            <% end %>
            <p class="m-3"><i class="fas fa-clock"></i> <%= recipe.time  %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="col-12">
  <div class="relative image--header">
    <%= cl_image_tag @recipe.photo.key, class: "img-cover img-300 gradient--image-primary" %>
  </div>
</div>

<div class="container-fluid mt-3 text-center">
  <div class="header bold text-gray1  mt-3">
    <%= @recipe.name%>
  </div>
  <div class="d-flex align-items-center justify-content-center gap-4 py-3">

    <!-- bookmark toggle -->
    <div class="d-flex h-full global_bookmark align-items-center gap-1">
      <% favourite = Favourite.find_by(user:current_user, recipe: @recipe)  %>
      <%if favourite %>
        <%= link_to user_favourite_path(current_user, favourite), class: "icon_button text-decoration-none align-items-center gap-1", remote: true, method: :delete do%>
          <%= image_tag "icon/bookmark-active.svg", class: "icon" %>
          <div class="small text-primary1">Saved</div>
        <% end %>
      <% else %>
        <%= link_to recipe_favourites_path(@recipe), class: "icon_button text-decoration-none align-items-center gap-1", remote: true, method: :post do %>
          <%= image_tag "icon/bookmark.svg", class: "icon" %>
          <div class="small text-primary1">Save</div>
        <% end %>
      <% end %>
    </div>

    <!-- bookmark toggle end -->



    <!-- rate -->
    <%# ###MODALS %>
  <div class="modal--review  sign-in " data-controller="demo">
    <%# ###REVIEW MODAL %>
    <div class="modal" data-demo-target="modal" data-controller="modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="fw-semibold fs-1">Leave  review</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" data-action="click->modal#close" ></button>
          </div>
          <div class="modal-body p-5">
            <div class="" data-controller="rating">
              <%= simple_form_for [ @recipe, @review ] do |f| %>
                <%= f.input :content, input_html: { class: "gray-border-rounded"} %>
                <%= f.input :rating, as: :hidden,  input_html: { class: "gray-border-rounded", data: { 'rating-target': 'rating' }}, wrapper_html: { class: 'js-linked' } %>
                <br>
                <label class="mb-2">Rating</label>
                <div class="rating d-flex align-item-center" >
                  <label>
                    <input type="radio" name="stars" value="1" data-action="click->rating#getValue1" data-rating-target="link1"/>
                    <span class="icon">★</span>
                  </label>
                  <label>
                    <input type="radio" name="stars" value="2" data-action="click->rating#getValue2" data-rating-target="link2"/>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                  </label>
                  <label>
                    <input type="radio" name="stars" value="3" data-action="click->rating#getValue3" data-rating-target="link3"/>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                  </label>
                  <label>
                    <input type="radio" name="stars" value="4" data-action="click->rating#getValue4" data-rating-target="link4"/>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                  </label>
                  <label>
                    <input type="radio" name="stars" value="5" data-action="click->rating#getValue5" data-rating-target="link5"/>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                  </label>
                </div>
                <hr>
              <%= f.submit "Submit review", class: "btn btn-primary" %>
            <% end %>
           </div>
          </div>
        </div>
      </div>
    </div>
    <%# END OF REVIEW MODAL %>
    <%# CTA BUTTONS %>
    <%= button_to '#', class:"small text-primary1 border-0 bg-color-white d-flex h-full global_bookmark  align-items-center gap-1", :data => {  :action => 'demo#launchDemo' } do %>
      <%= image_tag "icon/message.svg", class: "icon" %>
          Leave a review
        <% end %>
    <%# link_to "Profile", profile_path(@profile.id, param1: 'value1', param2: 'value2'), method: :post %>
  </div>
<%# ### END MODALS %>

    <!-- rate end -->
  </div>
</div>




<div class="recipe-info d-flex justify-content-between w-full py-3 px-4 my-3 text-gray2 small bg-color-primary5">
  <div class="text-center">
    Difficulty <br><span class="bold text-gray1"> <%= @recipe.difficulty %></span>
  </div>
  <div class="text-center">
    Time <br><span class="bold text-gray1"> <%= @recipe.time %></span>
  </div>
  <div class="text-center">
    Servings <br><span class="bold text-gray1"> <%= @recipe.serves %></span>
  </div>
</div>


<div class="container-fluid mt-4">
  <h2 class="large bold text-gray1">Ingredients</h2>
  <ul class="text-gray2 small ps-0 pt-1">
    <% @recipe.ingredients.split('--').each do |ingredient| %>
      <div class="ingredient--info d-flex flex-row my-2 bg-color-primary5 text-gray1 px-3 py-3 border--round--10">
        <input  class="me-2"type="checkbox" aria-label="Checkbox for following text input"> <li class="list-group-item pt-1"> <%= ingredient %></li>
      </div>
    <% end %>
  </ul>
</div>


<%# <div class="container-fluid mt-3"> %>
  <%# <ul class="text-gray2 small ps-0"> %>
    <%# <% @recipe.steps.split('--').each_with_index do |step, index| %>
      <%# <h2 class="normal bold text-gray1">Step <%= index + 1 %>
      <%# <li class="list-group-item pt-1"> <%= step %>
    <%# <% end %>
  <%# </ul> %>
<%# </div> %>





  <%= render partial: "cooking_modal", locals: {  } %>



    <%# CTA BUTTONS %>

    <div class="">
      <div class="action--buttons">
        <button type="button" class="btn btn-primary " data-action= 'demo1#launchDemo' >Start Cooking!</button>
      </div>
    </div>

    <%# link_to "Profile", profile_path(@profile.id, param1: 'value1', param2: 'value2'), method: :post %>
  </div>
<%# ### END MODALS %>
</div>


<%# REVIEWS SECTION %>
<hr class="text-gray3 mx-3 d-flex justify-content-center ">

<div class="review--section mx-3 mt-5 mb-5">
  <div class="d-flex align-items-center justify-content-between pb-3">
    <!-- Reviews title -->
    <div class="d-flex ">
       <h2 class="text-gray1 large bold mb-0">Reviews</h2>
    </div>
    <!-- Reviews title end -->
    <!-- button modal -->
    <div class="d-flex">
         <%# ###MODALS %>
  <div class="modal--review container sign-in ps-0" data-controller="demo">
    <%# ###REVIEW MODAL %>
    <div class="modal" data-demo-target="modal" data-controller="modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="fw-semibold fs-2">Leave  review</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" data-action="click->modal#close" ></button>
          </div>
          <div class="modal-body p-5">
            <div class="" data-controller="rating">
              <%= simple_form_for [ @recipe, @review ] do |f| %>
                <%= f.input :content, input_html: { class: "gray-border-rounded"} %>
                <%= f.input :rating, as: :hidden,  input_html: { class: "gray-border-rounded", data: { 'rating-target': 'rating' }}, wrapper_html: { class: 'js-linked' } %>
                <br>
                <label class="mb-2">Rating</label>
                <div class="rating d-flex align-item-center" >
                  <label>
                    <input type="radio" name="stars" value="1" data-action="click->rating#getValue1" data-rating-target="link1"/>
                    <span class="icon">★</span>
                  </label>
                  <label>
                    <input type="radio" name="stars" value="2" data-action="click->rating#getValue2" data-rating-target="link2"/>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                  </label>
                  <label>
                    <input type="radio" name="stars" value="3" data-action="click->rating#getValue3" data-rating-target="link3"/>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                  </label>
                  <label>
                    <input type="radio" name="stars" value="4" data-action="click->rating#getValue4" data-rating-target="link4"/>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                  </label>
                  <label>
                    <input type="radio" name="stars" value="5" data-action="click->rating#getValue5" data-rating-target="link5"/>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                    <span class="icon">★</span>
                  </label>
                </div>
                <hr>
              <%= f.submit "Submit review", class: "btn btn-primary" %>
            <% end %>
           </div>
          </div>
        </div>
      </div>
    </div>

    <%# END OF REVIEW MODAL %>

    <%# CTA BUTTONS %>

    <%= button_to '#', class:"small text-primary1 border-0 bg-color-white", :data => {  :action => 'demo#launchDemo' } do %>
      <%= image_tag "icon/message.svg", class: "icon" %>
          Leave a review
        <% end %>
    <%# link_to "Profile", profile_path(@profile.id, param1: 'value1', param2: 'value2'), method: :post %>
  </div>
<%# ### END MODALS %>




    </div>
    <!-- button modal end -->
   </div>



  <div class="pb-2">
  <% @recipe.reviews.sample(3).each do |review| %>
      <div class="comment mt-3">
        <div class="comment-heading gap-1">
          <% if review.user.photo.attached? %>
            <%= cl_image_tag review.user.photo.key , class: "mr-2 rounded", 'aria-haspopup': true, 'aria-expanded': false, size: "32x32" %>
          <% else %>
            <%= image_tag "https://cdn-icons-png.flaticon.com/512/190/190673.png?w=360", class: "mr-2 rounded", 'aria-haspopup': true, 'aria-expanded': false, size: "32x32" %>
          <% end %>
          <div class="comment-info">
            <p class="text-gray1"><strong><%= review.user.fullname%> </strong> <%= review.created_at.strftime("%d/%m/%Y") %></p>
          </div>
        </div>

      </div>

      <div class="comment-body text-gray1 ms-5">
        <p class="media-body pb-3 mb-0 small lh-125  d-flex">
            <%= review.content %>

            <%= ("⭐️" * review.rating )  %>
            <% if policy(review).destroy?%>
              <%= link_to  recipe_review_path(@recipe, review), class:"danger-text mx-2", method: :delete, remote: true do %>
                <i class="fas fa-times"></i>
              <% end %>
            <% end %>
        </p>
      </div>
  <% end %>
  </div>
  <% if @recipe.reviews.length === 0 %>
    <p class="text-gray3">No reviews yet</p>
  <% elsif  @recipe.reviews.length > 3 %>
    <%= link_to 'View more', recipe_reviews_path(@recipe), class:"mt-5 small text-primary1 text-decoration-none" %>
  <% end %>
</div>


<%# SEPARATOR %>
<hr class="text-gray3 mx-3 d-flex justify-content-center ">

<div class = "d-flex justify-content-start mx-3 mb-4">
   <% if policy(@recipe).destroy? %>
    <%= link_to "Delete Recipe", @recipe, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-danger decoration--none py-3 ps-0"%>
   <% end %>
</div>