config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get '/user' => "recipes#index", :as => :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :favourites, only: [:index, :show, :destroy]
    resources :memberships, only: [:index, :show, :destroy]
  end


  resources :recipes do
    collection do
      get :myrecipes
    end
    resources :favourites, only: [:new, :create]

    resources :reviews, only: [ :new, :create, :index, :destroy ]
  end

  resources :communities do

    resources :messages, except: [:destroy]
    resources :memberships

  end

  # resources :memberships, only: [] do
  #   collection do
  #     get :mymemberships
  #   end
  # end

  resources :messages, only: [:destroy]

end

app/views/shared/_footer.html.erb
<div class="footer align-items-center d-flex justify-content-center flex-column">
  <div class="social-media d-flex justify-content-center mt-5 ">
    <ul class="p-0">
      <a href="#" class="social--icons"><i class="fab fa-facebook fa-lg p-3"></i></a>
      <a href="#" class="social--icons"><i class="fab fa-twitter fa-lg p-3"></i></a>
      <a href="#" class="social--icons"><i class="fab fa-instagram fa-lg p-3"></i></a>
    </ul>
  </div>
  <h4>ⓒIngredible <%= current_year = Time.new.year %></h4>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to recipes_path, class: "navbar-brand" do %>
      <%= image_tag "ingredible-logos/ingredible-logos_white_only_face.svg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <%= image_tag "icon/menu.svg" %>
    </button>

    <div class="collapse navbar-collapse py-3" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Communities", communities_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Recipes", recipes_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Memberships", user_memberships_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Favorites", user_favourites_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
             <%= image_tag "https://cdn-icons-png.flaticon.com/512/190/190673.png?w=360", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create recipe", new_recipe_path, class: "dropdown-item" %>
              <%= link_to "Update profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "My Recipes",  myrecipes_recipes_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link sign-in-button" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>