config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get '/user' => "recipes#index", :as => :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :favourites, only: [:index, :show, :destroy]
    resources :memberships, only: [:index, :show, :destroy]
  end


  resources :recipes do
    collection do
      get :myrecipes
    end
    resources :favourites, only: [:new, :create]

    resources :reviews, only: [ :new, :create, :index, :destroy ]
  end

  resources :communities do

    resources :messages, except: [:destroy]
    resources :memberships

  end

  # resources :memberships, only: [] do
  #   collection do
  #     get :mymemberships
  #   end
  # end

  resources :messages, only: [:destroy]

end

app/models/community.rb
class Community < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
  has_one_attached :photo
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :update, :edit, :message]

  def index
    @communities = policy_scope(Community).includes(:memberships)

    # @membership = @communities.membership
    # authorize @membership

  end

  def show
    authorize @community
  end

  def edit
    authorize @community
  end

  def update
    authorize @community
    @community.update(community_params)
    redirect_to communities_path
  end

  def mycommunities
    @memberships = Membership.where(user_id: current_user.id)
  end

  private

  def community_params
    params.require(:community).permit(:name, :description)
  end

  def set_community
    @community = Community.find(params[:id])
  end
end

app/views/communities/edit.html.erb
<div class="container sign-in mt-5">

  <div class="form-inputs">
    <%= simple_form_for @community do |f| %>
      <%= f.input :name, input_html: { class: "gray-border-rounded" } %>
      <%= f.input :description , input_html: { class: "gray-border-rounded" }%>
  </div>
  <div class="form-actions mt-3">
      <%= f.button :submit, "Update",  class: "btn btn-primary mt-3 mb-3 text-white w-100 mb-5" %>
    <% end %>
  </div>
</div>

app/views/communities/index.html.erb
<div class="container">
  <h1 class="text-black mt-3 letter--space">Our communities!</h1>
  <div class="community--container">
    <% @communities.each  do |community|  %>
      <div class="community--card">
        <div class="community--card_header">
          <%= link_to  community_messages_path(community), method: :get , class:"" do %>
            <%= cl_image_tag community.photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
        </div>
        <div class="community--card__body">
          <h4 class= "fs-5 text"><%=  community.name %></h4>
          <p class="fs-6 text text-gray2"><%= community.description.truncate(70)  %></p>
        </div>
      </div>
    <% end%>
  </div>
</div>

app/views/communities/mycommunities.html.erb
<h1>My Communities</h1>

<% @memberships.each do |membership| %>
<p> <%= membership.community_id  %> </p>

<%end  %>

app/views/communities/show.html.erb
<div class="community--container ">
  <div class="header">
    <%= cl_image_tag @community.photo.key, class: "show--image border--round" %>
  </div>

  <div class="description mx-4">

    <h3><%= @community.name  %></h3>
    <p> <%= @community.description  %></p>
    <% if @community.memberships.one? { |member| member.user_id == current_user.id && member.community_id == @community.id} %>
     <%= button_to 'Enter',  community_messages_path(@community), method: :get, class:"btn btn-primary" %>
    <%else  %>
      <%= link_to 'Join',  community_memberships_path(@community), method: :post, class:" btn btn-primary" %>
    <% end %>
  </div>



</div>